WSS fix with interpolation, forced BPS and TPS power on
spartanracingelectric/VCU pull request #120
Opened 2021-08-19 04:42 UTC by vsawce

Fixed WSS. Issue was using FreqGet rather than ComplexGet, of which is necessary for the digital timer inputs.

An interpolation and RPM function were also added to smooth the WSS input.

BPS0 and TPS0 power functions were also forced back on from IO_POWER_OFF to IO_POWER_ON as IO_POWER_OFF causes the VCU to ignore BPS0 and TPS0 readings

2021-08-19 04:43 UTC, vsawce commented
May also need to look at type casting for the Wheelspeed RPM functions

2021-08-19 08:23 UTC, RustyPedrosa commented on main.c
> +    WheelSpeeds *wss = WheelSpeeds_new(WHEEL_DIAMETER, WHEEL_DIAMETER, NUM_BUMPS, NUM_BUMPS);
Consider having separate variables for front and rear

2021-08-19 09:28 UTC, RustyPedrosa requested changes

2021-08-19 09:28 UTC, RustyPedrosa commented on canManager.c
> +    canMessages[canMessageCount - 1].data[byteNum++] = ((ubyte2)(WheelSpeeds_getWheelSpeedRPM(wss, RR, FALSE) + 0.5)) >> 8;
I know I'm the one who wrote it this way originally, but..
Would it be better to store the reused calculation like this?
```
    ubyte2 tempRpm;
    tempRpm = WheelSpeeds_getWheelSpeedRPM(wss, FL, FALSE) + 0.5;  // Implicit cast of float4 to ubyte2
    canMessages[canMessageCount - 1].data[byteNum++] = tempRpm;
    canMessages[canMessageCount - 1].data[byteNum++] = tempRpm >> 8;
    tempRpm = WheelSpeeds_getWheelSpeedRPM(wss, FR, FALSE) + 0.5;  // Implicit cast of float4 to ubyte2
    canMessages[canMessageCount - 1].data[byteNum++] = tempRpm;
    canMessages[canMessageCount - 1].data[byteNum++] = tempRpm >> 8;
    ...
```

2021-08-19 09:28 UTC, RustyPedrosa commented on sensors.h
> +    ubyte4 timestamp;
Do you think we can/should move these to the WSS object?  Because putting this here adds 8 bytes of memory cost to _every_ sensor object.

You could argue that the timestamp might be valuable to more sensors.. but I'd say that most probably don't need it.

Side note: There's also 2 bytes of wasted memory for most sensors because of `ubyte4 sensorValue` (not your code), when most (but not all) sensors return 2 byte values).  As a matter of fact, if WSS was the only 4 byte sensor value, maybe we can change to ubyte2 throughout and probably eliminate some typecasting warnings.  I'll open a ticket for that investigation.  edit: Created issue #121

2021-08-19 09:28 UTC, RustyPedrosa commented on wheelSpeeds.c
> +                speed = me->speed_FL;
These are speed in m/s, not rpm

2021-08-19 09:28 UTC, RustyPedrosa commented on wheelSpeeds.c
> +    return speed*60.0;
Your RPM calculation also needs to take NUM_BUMPS into consideration

2021-08-19 09:38 UTC, RustyPedrosa commented on main.c
> +    WheelSpeeds *wss = WheelSpeeds_new(WHEEL_DIAMETER, WHEEL_DIAMETER, NUM_BUMPS, NUM_BUMPS);
I had to ask myself if these `#DEFINE`s were within scope here.
Answer: yes, since the header file is included
https://www.keil.com/support/docs/2589.htm

2021-08-19 16:56 UTC, vsawce commented on canManager.c
> +    canMessages[canMessageCount - 1].data[byteNum++] = ((ubyte2)(WheelSpeeds_getWheelSpeedRPM(wss, RR, FALSE) + 0.5)) >> 8;
I don't think it's necessary for this case because we're not dealing with volatile variables or interrupts? Or is there another reason why you would like to do this?

2021-08-19 16:58 UTC, vsawce commented on sensors.h
> +    ubyte4 timestamp;
That's a good point. I'll try testing these moved into the WSS object

2021-08-19 17:30 UTC, vsawce commented on wheelSpeeds.c
> +    return speed*60.0;
You're right, will add

2021-08-22 19:38 UTC, vsawce commented on safety.c
> +        //me->faults |= F_softBSPDFault;
Disabled actual relay control for softBSPD, it's causing choppy throttle response with current implementation

2021-08-22 22:52 UTC, RustyPedrosa commented on canManager.c
> +    canMessages[canMessageCount - 1].data[byteNum++] = ((ubyte2)(WheelSpeeds_getWheelSpeedRPM(wss, RR, FALSE) + 0.5)) >> 8;
Not necessary - just a thought.  I think I like the old way better, but the proposed way removes repeated code.

2021-08-22 23:13 UTC, RustyPedrosa requested changes

2021-08-22 23:13 UTC, RustyPedrosa commented on initializations.c
> +    //Maybe look for falling edge because we're using NPN/sinking WSS?
Created Issue #122 - please remove comments if you do another edit

2021-08-22 23:13 UTC, RustyPedrosa commented on sensors.c
> +    Sensor_WSS_RR.ioErr_signalGet = IO_PWD_ComplexGet(IO_PWD_11, &Sensor_WSS_RR.sensorValue, &pulseTrash, NULL);
I think you want these above where you set your `heldSensorValue`s, since these pull the new values from the TTC API and your held values won't get updated until the next main loop iteration

2021-08-22 23:25 UTC, RustyPedrosa commented on canManager.c
> +    //WSS RPM non-interpolated output
https://github.com/spartanracingelectric/VCU/issues/124

2021-08-24 11:53 UTC, RustyPedrosa commented
- Squash commits
- Rebase onto master

2023-08-13 00:00 UTC, closed without merging